name: ci/cd workflow1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from GitHub
        uses: actions/checkout@v6
   steps:
      - name: build the java app
        run: mvn clean install
   steps:
      - name: test the java app
        run: mvn clean test

