name: ci/cd workflow1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'

 # push:
  #  branches:
   #   - main
  # pull_request:
   # branches:
    #  - main
jobs:
  ci-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from GitHub
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: build the java app
        run: mvn clean install
      - name: test the java app
        run: mvn test
      - name: print env
        run: ${{inputs.environment.default}}

